#https://www.chezmoi.io/user-guide/include-files-from-elsewhere/#include-a-subdirectory-with-selected-files-from-a-url

{{if not (eq .chezmoi.os "darwin") }}
[".local/bin/gopass"]
  type = "file"
  url = "https://github.com/gopasspw/gopass/releases/download/v1.14.3/gopass-1.14.3-linux-amd64.tar.gz"
  executable = true
  extract = true 
  [".local/bin/gopass".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "gopass"] 
{{end}}

{{if not .colab}}
[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = false
  stripComponents = 1
{{end}}

{{if not .container}} # no point in adding imgcat for envs that do not support ssh
[".local/bin/imgcat"]
  type="file"
  url="https://iterm2.com/utilities/imgcat"
  executable = true
  exact = true
{{end}}

{{if eq .chezmoi.os "darwin" }}
[".hammerspoon"] 
  type="git-repo"
  url="https://github.com/PiotrCzapla/hammerspoon-config.git"
{{end}}
